apiVersion: v1
kind: Service
metadata:
  name: customer-service
  labels:
    name: customer-service
    app: nodejs-microservice-app
spec:
  type: LoadBalancer
  ports:
    - port: 8001
      targetPort: 8001
  selector:
    name: customer-app-pod
    app: nodejs-microservice-app
