apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-app-deploy
  labels:
    name: product-app-deploy
    app: nodejs-microservice-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: product-app-pod
      app: nodejs-microservice-app
    
  template:
    metadata:
      name: product-app-pod
      labels:
        name: product-app-pod
        app: nodejs-microservice-app
    spec:
      containers:
        - name: product-app
          image: docker.io/guguskyler/product-app:latest
          ports:
            - containerPort: 8002
          env:
          - name: APP_SECRET
            value: "jg_youtube_tutorial"
          - name: MONGODB_URI
            value: "mongodb://nosql-db/msytt_product"
          - name: MSG_QUEUE_URL
            value: "amqp://rabbitmq:5672"
          - name: EXCHANGE_NAME
            value: "ONLINE_STORE"
          - name: PORT
            value: "8002"
    