apiVersion: v1
kind: Service
metadata:
  name: shopping-service
  labels:
    name: shopping-service
    app: nodejs-microservice-app
spec:
  type: LoadBalancer
  ports:
    - port: 8003
      targetPort: 8003
  selector:
    name: shopping-app-pod
    app: nodejs-microservice-app