apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-app-deploy
  labels:
    name: shopping-app-deploy
    app: nodejs-microservice-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: shopping-app-pod
      app: nodejs-microservice-app
    
  template:
    metadata:
      name: shopping-app-pod
      labels:
        name: shopping-app-pod
        app: nodejs-microservice-app
    spec:
      containers:
        - name: shopping-app
          image: docker.io/guguskyler/shopping-app:latest
          ports:
            - containerPort: 8003
          env:
          - name: APP_SECRET
            value: "jg_youtube_tutorial"
          - name: MONGODB_URI
            value: "mongodb://nosql-db/msytt_shopping"
          - name: MSG_QUEUE_URL
            value: "amqp://rabbitmq:5672"
          - name: EXCHANGE_NAME
            value: "ONLINE_STORE"
          - name: PORT
            value: "8003"
    